# Generated by Django 4.0.5 on 2022-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
