# Generated by Django 4.0.5 on 2022-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='type',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
