# Generated by Django 4.0.5 on 2022-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_loved', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_loved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_loved',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
